num1 = float(input("ingresa el valor 1:"))
num2 = float(input("Ingrese el valor 2:"))

add = (num1 + num2)
print("suma: "(add))
sub = (num1 - num2)
print("resta: "(sub))
mult = (num1 * num2)
print("multiplicacion: "(mult))
div = (num1 / num2)
print("division: "(div))